### ISSUE TITLE
Pre-commit checks (Linting, code style, other checks)

### ISSUE THREAD

**Issue by Kaszanas** [Kaszanas/SC2_Datasets#39]
Overall it would be nice to have some pre-commit checks with formatting and linting applied for anyone that wishes to contribute to this repository.

Example configuration:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
exclude: |
    (?x)(
        ^output/|
        ^fonts/|
        ^charts/|
        ^old/
    )

```

It might be good to use ruff for linting.
